const ARTWORKS = [
  {
    id: 1,
    title: "Instagram Wall",
    artist: "Alex Croft",
    type: "Mural",
    lat: 22.2831, lng: 114.1536,
    photo: "",
    commissioned: true,
    address: "Graham Street at Hollywood Road, Central",
    hint: "Blocky, candy-colored tong lau windows cover an entire wall — one of the most photographed murals in the city, right by the wet market stalls of Graham Street.",
    radius: 60
  },
  {
    id: 2,
    title: "Space Invader Mosaic",
    artist: "Invader",
    type: "Installation",
    lat: 22.2850, lng: 114.1494,
    photo: "",
    commissioned: false,
    address: "Near Po Hing Fong, Sheung Wan",
    hint: "A tiny pixelated alien made of ceramic tiles clings to a wall above eye level — part of a French artist's secret worldwide 'invasion'. A few tiles nearby have vanished over the years, so look carefully.",
    radius: 40
  },
  {
    id: 3,
    title: "Hong Kong Encoded",
    artist: "Miguel Emerico",
    type: "Mural",
    lat: 22.2843, lng: 114.1497,
    photo: "",
    commissioned: true,
    address: "26 Tai Ping Shan Street, Sheung Wan",
    hint: "An entire alley wall packed with layered symbols, buildings and motifs of the city, painted by a Hong Kong-based Spanish artist.",
    radius: 60
  },
  {
    id: 4,
    title: "Power, Status, Peace",
    artist: "Riya Chandiramani",
    type: "Mural",
    lat: 22.2841, lng: 114.1498,
    photo: "",
    commissioned: true,
    address: "22-24 Tai Ping Shan Street, Sheung Wan",
    hint: "Indian and Chinese motifs swirl together around words like 'power' and 'peace' on a shopfront wall a few doors from the Museum of Medical Sciences.",
    radius: 50
  },
  {
    id: 5,
    title: "Kwong Fuk Geometry",
    artist: "Chen Ka-yan",
    type: "Mural",
    lat: 22.2848, lng: 114.1491,
    photo: "",
    commissioned: true,
    address: "Kwong Fuk Ancestral Hall, 40 Tai Ping Shan Street, Sheung Wan",
    hint: "Bold geometric patterns and prayer text wrap around a real ancestral hall run by the Tung Wah Group — look for the incense smoke drifting out the door.",
    radius: 55
  },
  {
    id: 6,
    title: "Skyline from the Mid-Levels",
    artist: "Carol Mui & Rebecca T Lin",
    type: "Mural",
    lat: 22.2836, lng: 114.1503,
    photo: "",
    commissioned: true,
    address: "Universal Building, 5-13 New Street, Tai Ping Shan",
    hint: "Hong Kong's concrete towers rise out of a leafy hillside on the side of an old tenement block — painted from the same Mid-Levels vantage point it depicts.",
    radius: 60
  },
  {
    id: 7,
    title: "Bruce Lee Portrait",
    artist: "Xeva",
    type: "Mural",
    lat: 22.2828, lng: 114.1489,
    photo: "",
    commissioned: true,
    address: "Tank Lane, Sheung Wan",
    hint: "A photorealistic tribute to Hong Kong's most famous martial artist fills this narrow lane connecting two steep streets.",
    radius: 45
  },
  {
    id: 8,
    title: "Figures in Motion",
    artist: "Alex Senna",
    type: "Mural",
    lat: 22.2826, lng: 114.1488,
    photo: "",
    commissioned: true,
    address: "Tank Lane at Bridges Street, Sheung Wan",
    hint: "Elongated black-and-white silhouettes stretch across a corner wall where Tank Lane meets Bridges Street.",
    radius: 45
  },
  {
    id: 9,
    title: "Melting Cartoons",
    artist: "Matt Gondek",
    type: "Mural",
    lat: 22.2833, lng: 114.1499,
    photo: "",
    commissioned: true,
    address: "Tank Lane at Lower Lascar Row, Sheung Wan",
    hint: "Familiar cartoon mice and ducks droop and melt down a wall near the antique stalls of Cat Street.",
    radius: 45
  },
  {
    id: 10,
    title: "Scratching the Surface",
    artist: "Vhils (Alexandre Farto)",
    type: "Installation",
    lat: 22.2862, lng: 114.1490,
    photo: "",
    commissioned: false,
    address: "Sai Street, Sheung Wan",
    hint: "A face is carved directly into the plaster and concrete of an old tong lau — no paint, just chiselled brick revealed layer by layer.",
    radius: 50
  },
  {
    id: 11,
    title: "Landscape to Dragon",
    artist: "WEST one & Megic",
    type: "Mural",
    lat: 22.2866, lng: 114.1487,
    photo: "",
    commissioned: true,
    address: "Lane between Upper Station Street and Sai Street, Sheung Wan",
    hint: "A traditional Chinese ink landscape slowly warps into hard geometric shapes and finally a dragon's head down this narrow lane.",
    radius: 50
  },
  {
    id: 12,
    title: "Treasure Map",
    artist: "KristopherH",
    type: "Mural",
    lat: 22.2836, lng: 114.1485,
    photo: "",
    commissioned: true,
    address: "Shin Hing Street at Hollywood Road, Sheung Wan",
    hint: "A six-faced creature and an old treasure map cover the corner wall outside a small bistro just off Hollywood Road.",
    radius: 45
  },
  {
    id: 13,
    title: "Bedu Wall",
    artist: "Elsa Jean de Dieu",
    type: "Mural",
    lat: 22.2833, lng: 114.1518,
    photo: "",
    commissioned: true,
    address: "Gough Street at Shin Hing Street, Sheung Wan",
    hint: "Bold black linework covers the wall beside a small Middle Eastern restaurant, signed with the artist's signature laughing face.",
    radius: 45
  },
  {
    id: 14,
    title: "Rhino (formerly Koi)",
    artist: "Christian Storm",
    type: "Mural",
    lat: 22.2843, lng: 114.1500,
    photo: "",
    commissioned: true,
    address: "Shing Wong Street at Hollywood Road, Sheung Wan",
    hint: "What started as leaping koi fish has since been repainted into a rhino on this corner wall — ask a local how many versions they remember.",
    radius: 50
  },
  {
    id: 15,
    title: "PMQ Pop Wall",
    artist: "D*face",
    type: "Mural",
    lat: 22.2826, lng: 114.1518,
    photo: "",
    commissioned: true,
    address: "PMQ, 35 Aberdeen Street, Central",
    hint: "A pop-art face grins from the wall of the old Police Married Quarters, now packed with design studios and market stalls.",
    radius: 60
  },
  {
    id: 16,
    title: "Indigo Memories",
    artist: "Hopare",
    type: "Installation",
    lat: 22.2829, lng: 114.1516,
    photo: "",
    commissioned: true,
    address: "PMQ, Staunton Street façade, Central",
    hint: "A sweeping large-scale installation covers PMQ's Staunton Street side, added during the most recent street art festival.",
    radius: 60
  },
  {
    id: 17,
    title: "Fox Multi Coloured",
    artist: "Rukkit Kuanhawate",
    type: "Mural",
    lat: 22.2870, lng: 114.1485,
    photo: "",
    commissioned: true,
    address: "Upper Station Street, Sheung Wan",
    hint: "A rainbow-colored fox stretches across a shutter on this quiet residential street north of Tai Ping Shan.",
    radius: 50
  },
  {
    id: 18,
    title: "The Pet of the Archaeologist",
    artist: "Barlo",
    type: "Mural",
    lat: 22.2868, lng: 114.1483,
    photo: "",
    commissioned: true,
    address: "Alley behind 18 Upper Station Street, Sheung Wan",
    hint: "A strange cross-sectioned creature — half specimen, half porcelain figure — hides in a narrow alley behind the street.",
    radius: 40
  },
  {
    id: 19,
    title: "Rich View Characters",
    artist: "Zlism",
    type: "Mural",
    lat: 22.2864, lng: 114.1481,
    photo: "",
    commissioned: true,
    address: "Rich View Terrace, Sheung Wan",
    hint: "A crowd of brightly colored, oddly-shaped characters climbs the side wall of a small terrace block.",
    radius: 45
  },
  {
    id: 20,
    title: "Art Deco Portrait",
    artist: "Neil Wang",
    type: "Mural",
    lat: 22.2846, lng: 114.1494,
    photo: "",
    commissioned: true,
    address: "21 Square Street, Sheung Wan",
    hint: "A glamorous art-deco face in clean lines and floral decoration looks out from a quiet residential street.",
    radius: 45
  }
];
